Build and push docker image

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,10 @@
 name: Main workflow
 on: push
+env: # Set the secret as an input
+  github_username: ${{ github.actor }}
+  github_password: ${{ secrets.GITHUB_TOKEN }} # Must be made available to the workflow
+  GIT_COMMIT: ${{ github.sha }}
+
 jobs:
   Build:
     runs-on: ubuntu-latest
@@ -33,4 +38,30 @@ jobs:
           DEFAULT_BRANCH: main
           # To report GitHub Actions status checks
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          DISABLE_ERRORS: true 
+          DISABLE_ERRORS: true
+
+  Docker-image:
+    runs-on: ubuntu-latest
+    needs: [Build]
+    permissions:
+      packages: write
+    steps:
+    - name: Download code
+      uses: actions/download-artifact@v4
+      with:
+        name: code
+        path: .
+    - name: Validate Docker username is all lowercase
+      id: validate_lower
+      run: |
+        if [[ "${{ env.github_username }}" =~ [A-Z] ]]; then
+          echo "::error::Validation Failed: GitHub username '${{ env.github_username }}' cannot contain uppercase characters."
+          exit 1
+        else
+          echo "Docker username format is valid."
+        fi
+      shell: bash
+    - name: build docker
+      run: bash ci/build-docker.sh
+    - name: push docker
+      run: bash ci/push-docker.sh
